// qa/src/App.tsx
import { useState } from 'react'
import { Routes, Route, NavLink } from 'react-router-dom'
import ScrollToTop from './components/ScrollToTop'
import ThemeToggle from './components/ThemeToggle'
import Home from './pages/Home'
import TestingFundamentals from './pages/fundamentals/TestingFundamentals'
import TestDesign from './pages/fundamentals/TestDesign'
import BugReporting from './pages/process/BugReporting'
import TestPlan from './pages/process/TestPlan'
import WebTesting from './pages/practice/WebTesting'
import APITesting from './pages/practice/APITesting'
import AutomationBasics from './pages/automation/AutomationBasics'
import TestPyramid from './pages/automation/TestPyramid'
import AutomationArchitecture from './pages/automation/AutomationArchitecture'
import QAMetrics from './pages/advanced/QAMetrics'
import CICDTesting from './pages/advanced/CICDTesting'
import SpecializedTesting from './pages/specialized/SpecializedTesting'
import BugTriagePractice from './pages/practice/BugTriagePractice'

export default function App() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() =>
    localStorage.getItem('qa-sidebar-collapsed') === 'true'
  )

  const handleNavClick = () => setMobileMenuOpen(false)

  const toggleSidebar = () => {
    setSidebarCollapsed(prev => {
      localStorage.setItem('qa-sidebar-collapsed', String(!prev))
      return !prev
    })
  }

  return (
    <>
      <ScrollToTop />

      <header className="mobile-header">
        <button
          className="hamburger-btn"
          onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          aria-label="Toggle menu"
        >
          {mobileMenuOpen ? '✕' : '☰'}
        </button>
        <h1>🧪 QA 101</h1>
      </header>

      {mobileMenuOpen && (
        <div className="mobile-overlay" onClick={() => setMobileMenuOpen(false)} />
      )}

      <div className={`app-layout ${sidebarCollapsed ? 'layout-collapsed' : ''}`}>
        <aside className={`sidebar ${mobileMenuOpen ? 'sidebar-open' : ''} ${sidebarCollapsed ? 'sidebar-collapsed' : ''}`}>
          <div className="sidebar-header">
            <div className="sidebar-header-top">
              <h1>🧪 QA 101</h1>
              <ThemeToggle />
            </div>
            <p>Тестирование и QA</p>
            <a href={import.meta.env.VITE_DEPLOY_TARGET === 'github-pages' ? new URL('..', window.location.origin + import.meta.env.BASE_URL).toString() : 'http://localhost:3200'} className="back-to-index">← Все плейграунды</a>
          </div>

          <nav className="nav-section">
            <NavLink to="/" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} end onClick={handleNavClick}>
              <span className="nav-link-icon">🏠</span>
              Главная
            </NavLink>

            <div className="nav-section-title">Основы</div>

            <NavLink to="/fundamentals/basics" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📖</span>
              Теория тестирования
            </NavLink>

            <NavLink to="/fundamentals/test-design" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🎨</span>
              Тест-дизайн
            </NavLink>

            <div className="nav-section-title">Процессы</div>

            <NavLink to="/process/bug-reporting" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🐛</span>
              Баг-репорты
            </NavLink>

            <NavLink to="/process/test-plan" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📋</span>
              Тест-план и чек-листы
            </NavLink>

            <div className="nav-section-title">Практика</div>

            <NavLink to="/practice/web-testing" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🌐</span>
              Тестирование Web
            </NavLink>

            <NavLink to="/practice/api-testing" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔌</span>
              Тестирование API
            </NavLink>

            <NavLink to="/practice/bug-triage" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🐛</span>
              Bug Triage & Практика
            </NavLink>

            <div className="nav-section-title">Автоматизация</div>

            <NavLink to="/automation/basics" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🤖</span>
              Основы автоматизации
            </NavLink>

            <NavLink to="/automation/pyramid" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔺</span>
              Пирамида тестирования
            </NavLink>

            <NavLink to="/automation/architecture" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🏗️</span>
              Архитектура и Flaky
            </NavLink>

            <div className="nav-section-title">Продвинутое</div>

            <NavLink to="/advanced/metrics" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📊</span>
              QA-метрики
            </NavLink>

            <NavLink to="/advanced/cicd" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔄</span>
              CI/CD и тесты
            </NavLink>

            <div className="nav-section-title">Специализация</div>

            <NavLink to="/specialized/testing" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🎯</span>
              Mobile, Security, Perf
            </NavLink>

            <button className="sidebar-collapse-btn" onClick={toggleSidebar}>
              {sidebarCollapsed ? '»' : '«'}
              <span className="collapse-text">{sidebarCollapsed ? 'Развернуть' : 'Свернуть'}</span>
            </button>
          </nav>
        </aside>

        <main className="main-content">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/fundamentals/basics" element={<TestingFundamentals />} />
            <Route path="/fundamentals/test-design" element={<TestDesign />} />
            <Route path="/process/bug-reporting" element={<BugReporting />} />
            <Route path="/process/test-plan" element={<TestPlan />} />
            <Route path="/practice/web-testing" element={<WebTesting />} />
            <Route path="/practice/api-testing" element={<APITesting />} />
            <Route path="/practice/bug-triage" element={<BugTriagePractice />} />
            <Route path="/automation/basics" element={<AutomationBasics />} />
            <Route path="/automation/pyramid" element={<TestPyramid />} />
            <Route path="/automation/architecture" element={<AutomationArchitecture />} />
            <Route path="/advanced/metrics" element={<QAMetrics />} />
            <Route path="/advanced/cicd" element={<CICDTesting />} />
            <Route path="/specialized/testing" element={<SpecializedTesting />} />
          </Routes>
        </main>
      </div>
    </>
  )
}

// vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink, RouterView, useRoute } from 'vue-router'
import ThemeToggle from './components/ThemeToggle.vue'

const mobileMenuOpen = ref(false)
const sidebarCollapsed = ref(localStorage.getItem('vue-sidebar-collapsed') === 'true')
const indexHref = import.meta.env.VITE_DEPLOY_TARGET === 'github-pages'
  ? new URL('..', window.location.origin + import.meta.env.BASE_URL).toString()
  : 'http://localhost:3200'
const route = useRoute()

const handleNavClick = () => {
  mobileMenuOpen.value = false
}

const toggleSidebar = () => {
  sidebarCollapsed.value = !sidebarCollapsed.value
  localStorage.setItem('vue-sidebar-collapsed', String(sidebarCollapsed.value))
}

const isActive = (path: string) => {
  return route.path === path
}
</script>

<template>
  <!-- Mobile Header -->
  <header class="mobile-header">
    <button 
      class="hamburger-btn" 
      @click="mobileMenuOpen = !mobileMenuOpen"
      aria-label="Toggle menu"
    >
      {{ mobileMenuOpen ? '✕' : '☰' }}
    </button>
    <h1><img src="/logo.svg" alt="" width="28" height="28" style="margin-right: 8px" /> Vue 101</h1>
  </header>

  <!-- Mobile Menu Overlay -->
  <div 
    v-if="mobileMenuOpen" 
    class="mobile-overlay" 
    @click="mobileMenuOpen = false" 
  />

  <div :class="['app-layout', { 'layout-collapsed': sidebarCollapsed }]">
    <aside :class="['sidebar', { 'sidebar-open': mobileMenuOpen, 'sidebar-collapsed': sidebarCollapsed }]">
      <div class="sidebar-header">
        <div class="sidebar-header-top">
          <h1><img src="/logo.svg" alt="" width="28" height="28" style="margin-right: 8px" /> Vue 101</h1>
          <ThemeToggle />
        </div>
        <p>Интерактивный курс</p>
        <a :href="indexHref" class="back-to-index">← Все плейграунды</a>
      </div>

      <nav class="nav-section">
        <RouterLink 
          to="/" 
          :class="['nav-link', { active: isActive('/') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🏠</span>
          Главная
        </RouterLink>

        <div class="nav-section-title">Основы</div>
        
        <RouterLink 
          to="/basics/template-syntax" 
          :class="['nav-link', { active: isActive('/basics/template-syntax') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📝</span>
          Template Syntax
        </RouterLink>
        
        <RouterLink 
          to="/basics/styling" 
          :class="['nav-link', { active: isActive('/basics/styling') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎨</span>
          Стилизация
        </RouterLink>

        <RouterLink 
          to="/basics/v-model" 
          :class="['nav-link', { active: isActive('/basics/v-model') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔗</span>
          v-model
        </RouterLink>

        <div class="nav-section-title">Реактивность</div>
        
        <RouterLink 
          to="/reactivity/ref" 
          :class="['nav-link', { active: isActive('/reactivity/ref') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📦</span>
          ref()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/reactive" 
          :class="['nav-link', { active: isActive('/reactivity/reactive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⚡</span>
          reactive()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/computed" 
          :class="['nav-link', { active: isActive('/reactivity/computed') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧮</span>
          computed()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/watch" 
          :class="['nav-link', { active: isActive('/reactivity/watch') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">👁️</span>
          watch / watchEffect
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/comparison" 
          :class="['nav-link', { active: isActive('/reactivity/comparison') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔬</span>
          ref vs shallowRef
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/overview" 
          :class="['nav-link', { active: isActive('/reactivity/overview') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔄</span>
          Обзор реактивности
        </RouterLink>

        <div class="nav-section-title">Жизненный цикл</div>
        
        <RouterLink 
          to="/lifecycle/hooks" 
          :class="['nav-link', { active: isActive('/lifecycle/hooks') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔁</span>
          Lifecycle Hooks
        </RouterLink>

        <div class="nav-section-title">Компоненты</div>
        
        <RouterLink 
          to="/components/props-emits" 
          :class="['nav-link', { active: isActive('/components/props-emits') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📤</span>
          Props & Emits
        </RouterLink>
        
        <RouterLink 
          to="/components/slots" 
          :class="['nav-link', { active: isActive('/components/slots') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎰</span>
          Slots
        </RouterLink>
        
        <RouterLink 
          to="/components/provide-inject" 
          :class="['nav-link', { active: isActive('/components/provide-inject') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">💉</span>
          Provide / Inject
        </RouterLink>

        <div class="nav-section-title">Composables</div>
        
        <RouterLink 
          to="/composables/intro" 
          :class="['nav-link', { active: isActive('/composables/intro') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧩</span>
          Введение
        </RouterLink>

        <div class="nav-section-title">State Management</div>
        
        <RouterLink 
          to="/state/pinia" 
          :class="['nav-link', { active: isActive('/state/pinia') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🍍</span>
          Pinia
        </RouterLink>

        <div class="nav-section-title">Паттерны</div>
        
        <RouterLink 
          to="/patterns/components" 
          :class="['nav-link', { active: isActive('/patterns/components') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧱</span>
          Компоненты
        </RouterLink>

        <div class="nav-section-title">Vue 3.5+</div>
        
        <RouterLink 
          to="/versions/vue35" 
          :class="['nav-link', { active: isActive('/versions/vue35') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🚀</span>
          Новые фичи
        </RouterLink>

        <div class="nav-section-title">Демонстрации</div>
        
        <RouterLink 
          to="/demos/interactive" 
          :class="['nav-link', { active: isActive('/demos/interactive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎮</span>
          Интерактивные демо
        </RouterLink>
        <RouterLink 
          to="/demos/teleport" 
          :class="['nav-link', { active: isActive('/demos/teleport') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">👻</span>
          Teleport
        </RouterLink>

        <div class="nav-section-title">Продвинутое</div>
        
        <RouterLink 
          to="/advanced/custom-directives" 
          :class="['nav-link', { active: isActive('/advanced/custom-directives') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎯</span>
          Кастомные директивы
        </RouterLink>
        
        <RouterLink 
          to="/advanced/next-tick" 
          :class="['nav-link', { active: isActive('/advanced/next-tick') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⏱️</span>
          nextTick
        </RouterLink>
        
        <RouterLink 
          to="/advanced/keep-alive" 
          :class="['nav-link', { active: isActive('/advanced/keep-alive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📦</span>
          KeepAlive
        </RouterLink>
        
        <RouterLink 
          to="/advanced/error-handling" 
          :class="['nav-link', { active: isActive('/advanced/error-handling') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🛡️</span>
          Обработка ошибок
        </RouterLink>
        
        <RouterLink 
          to="/advanced/reactivity-caveats" 
          :class="['nav-link', { active: isActive('/advanced/reactivity-caveats') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⚡</span>
          Подводные камни
        </RouterLink>

        <RouterLink 
          to="/advanced/reactivity-deep" 
          :class="['nav-link', { active: isActive('/advanced/reactivity-deep') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔬</span>
          Продвинутая реактивность
        </RouterLink>

        <div class="nav-section-title">Тестирование</div>

        <RouterLink
          to="/testing/guide"
          :class="['nav-link', { active: $route.path === '/testing/guide' }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧪</span>
          Vitest + VTU
        </RouterLink>

        <div class="nav-section-title">Роутинг и Архитектура</div>

        <RouterLink
          to="/routing/architecture"
          :class="['nav-link', { active: $route.path === '/routing/architecture' }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🗺️</span>
          Router и Архитектура
        </RouterLink>

        <button class="sidebar-collapse-btn" @click="toggleSidebar">
          {{ sidebarCollapsed ? '»' : '«' }}
          <span class="collapse-text">{{ sidebarCollapsed ? 'Развернуть' : 'Свернуть' }}</span>
        </button>
      </nav>
    </aside>

    <main class="main-content">
      <RouterView />
    </main>
  </div>
</template>
