// vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { RouterLink, RouterView, useRoute } from 'vue-router'
import ThemeToggle from './components/ThemeToggle.vue'

const mobileMenuOpen = ref(false)
const sidebarCollapsed = ref(localStorage.getItem('vue-sidebar-collapsed') === 'true')
const indexHref = import.meta.env.VITE_DEPLOY_TARGET === 'github-pages'
  ? new URL('..', window.location.origin + import.meta.env.BASE_URL).toString()
  : 'http://localhost:3200'
const route = useRoute()

const handleNavClick = () => {
  mobileMenuOpen.value = false
}

const toggleSidebar = () => {
  sidebarCollapsed.value = !sidebarCollapsed.value
  localStorage.setItem('vue-sidebar-collapsed', String(sidebarCollapsed.value))
}

const isActive = (path: string) => {
  return route.path === path
}
</script>

<template>
  <!-- Mobile Header -->
  <header class="mobile-header">
    <button 
      class="hamburger-btn" 
      @click="mobileMenuOpen = !mobileMenuOpen"
      aria-label="Toggle menu"
    >
      {{ mobileMenuOpen ? '✕' : '☰' }}
    </button>
    <h1><img src="/logo.svg" alt="" width="28" height="28" style="margin-right: 8px" /> Vue 101</h1>
  </header>

  <!-- Mobile Menu Overlay -->
  <div 
    v-if="mobileMenuOpen" 
    class="mobile-overlay" 
    @click="mobileMenuOpen = false" 
  />

  <div :class="['app-layout', { 'layout-collapsed': sidebarCollapsed }]">
    <aside :class="['sidebar', { 'sidebar-open': mobileMenuOpen, 'sidebar-collapsed': sidebarCollapsed }]">
      <div class="sidebar-header">
        <div class="sidebar-header-top">
          <h1><img src="/logo.svg" alt="" width="28" height="28" style="margin-right: 8px" /> Vue 101</h1>
          <ThemeToggle />
        </div>
        <p>Интерактивный курс</p>
        <a :href="indexHref" class="back-to-index">← Все плейграунды</a>
      </div>

      <nav class="nav-section">
        <RouterLink 
          to="/" 
          :class="['nav-link', { active: isActive('/') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🏠</span>
          Главная
        </RouterLink>

        <div class="nav-section-title">Основы</div>
        
        <RouterLink 
          to="/basics/template-syntax" 
          :class="['nav-link', { active: isActive('/basics/template-syntax') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📝</span>
          Template Syntax
        </RouterLink>
        
        <RouterLink 
          to="/basics/styling" 
          :class="['nav-link', { active: isActive('/basics/styling') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎨</span>
          Стилизация
        </RouterLink>

        <RouterLink 
          to="/basics/v-model" 
          :class="['nav-link', { active: isActive('/basics/v-model') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔗</span>
          v-model
        </RouterLink>

        <div class="nav-section-title">Реактивность</div>
        
        <RouterLink 
          to="/reactivity/ref" 
          :class="['nav-link', { active: isActive('/reactivity/ref') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📦</span>
          ref()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/reactive" 
          :class="['nav-link', { active: isActive('/reactivity/reactive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⚡</span>
          reactive()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/computed" 
          :class="['nav-link', { active: isActive('/reactivity/computed') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧮</span>
          computed()
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/watch" 
          :class="['nav-link', { active: isActive('/reactivity/watch') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">👁️</span>
          watch / watchEffect
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/comparison" 
          :class="['nav-link', { active: isActive('/reactivity/comparison') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔬</span>
          ref vs shallowRef
        </RouterLink>
        
        <RouterLink 
          to="/reactivity/overview" 
          :class="['nav-link', { active: isActive('/reactivity/overview') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔄</span>
          Обзор реактивности
        </RouterLink>

        <div class="nav-section-title">Жизненный цикл</div>
        
        <RouterLink 
          to="/lifecycle/hooks" 
          :class="['nav-link', { active: isActive('/lifecycle/hooks') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔁</span>
          Lifecycle Hooks
        </RouterLink>

        <div class="nav-section-title">Компоненты</div>
        
        <RouterLink 
          to="/components/props-emits" 
          :class="['nav-link', { active: isActive('/components/props-emits') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📤</span>
          Props & Emits
        </RouterLink>
        
        <RouterLink 
          to="/components/slots" 
          :class="['nav-link', { active: isActive('/components/slots') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎰</span>
          Slots
        </RouterLink>
        
        <RouterLink 
          to="/components/provide-inject" 
          :class="['nav-link', { active: isActive('/components/provide-inject') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">💉</span>
          Provide / Inject
        </RouterLink>

        <div class="nav-section-title">Composables</div>
        
        <RouterLink 
          to="/composables/intro" 
          :class="['nav-link', { active: isActive('/composables/intro') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧩</span>
          Введение
        </RouterLink>

        <div class="nav-section-title">State Management</div>
        
        <RouterLink 
          to="/state/pinia" 
          :class="['nav-link', { active: isActive('/state/pinia') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🍍</span>
          Pinia
        </RouterLink>

        <div class="nav-section-title">Паттерны</div>
        
        <RouterLink 
          to="/patterns/components" 
          :class="['nav-link', { active: isActive('/patterns/components') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧱</span>
          Компоненты
        </RouterLink>

        <div class="nav-section-title">Vue 3.5+</div>
        
        <RouterLink 
          to="/versions/vue35" 
          :class="['nav-link', { active: isActive('/versions/vue35') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🚀</span>
          Новые фичи
        </RouterLink>

        <div class="nav-section-title">Демонстрации</div>
        
        <RouterLink 
          to="/demos/interactive" 
          :class="['nav-link', { active: isActive('/demos/interactive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎮</span>
          Интерактивные демо
        </RouterLink>
        <RouterLink 
          to="/demos/teleport" 
          :class="['nav-link', { active: isActive('/demos/teleport') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">👻</span>
          Teleport
        </RouterLink>

        <div class="nav-section-title">Продвинутое</div>
        
        <RouterLink 
          to="/advanced/custom-directives" 
          :class="['nav-link', { active: isActive('/advanced/custom-directives') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🎯</span>
          Кастомные директивы
        </RouterLink>
        
        <RouterLink 
          to="/advanced/next-tick" 
          :class="['nav-link', { active: isActive('/advanced/next-tick') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⏱️</span>
          nextTick
        </RouterLink>
        
        <RouterLink 
          to="/advanced/keep-alive" 
          :class="['nav-link', { active: isActive('/advanced/keep-alive') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">📦</span>
          KeepAlive
        </RouterLink>
        
        <RouterLink 
          to="/advanced/error-handling" 
          :class="['nav-link', { active: isActive('/advanced/error-handling') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🛡️</span>
          Обработка ошибок
        </RouterLink>
        
        <RouterLink 
          to="/advanced/reactivity-caveats" 
          :class="['nav-link', { active: isActive('/advanced/reactivity-caveats') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">⚡</span>
          Подводные камни
        </RouterLink>

        <RouterLink 
          to="/advanced/reactivity-deep" 
          :class="['nav-link', { active: isActive('/advanced/reactivity-deep') }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🔬</span>
          Продвинутая реактивность
        </RouterLink>

        <div class="nav-section-title">Тестирование</div>

        <RouterLink
          to="/testing/guide"
          :class="['nav-link', { active: $route.path === '/testing/guide' }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🧪</span>
          Vitest + VTU
        </RouterLink>

        <div class="nav-section-title">Роутинг и Архитектура</div>

        <RouterLink
          to="/routing/architecture"
          :class="['nav-link', { active: $route.path === '/routing/architecture' }]"
          @click="handleNavClick"
        >
          <span class="nav-link-icon">🗺️</span>
          Router и Архитектура
        </RouterLink>

        <button class="sidebar-collapse-btn" @click="toggleSidebar">
          {{ sidebarCollapsed ? '»' : '«' }}
          <span class="collapse-text">{{ sidebarCollapsed ? 'Развернуть' : 'Свернуть' }}</span>
        </button>
      </nav>
    </aside>

    <main class="main-content">
      <RouterView />
    </main>
  </div>
</template>

// swiftui/src/App.tsx
import { useState } from 'react'
import { Routes, Route, NavLink } from 'react-router-dom'
import ScrollToTop from './components/ScrollToTop'
import Home from './pages/Home'
import ViewsModifiersPage from './pages/ViewsModifiersPage'
import LayoutPage from './pages/LayoutPage'
import StatePage from './pages/StatePage'
import BindingPage from './pages/BindingPage'
import ObservablePage from './pages/ObservablePage'
import EnvironmentPage from './pages/EnvironmentPage'
import NavigationPage from './pages/NavigationPage'
import ListsFormsPage from './pages/ListsFormsPage'
import AnimationsPage from './pages/AnimationsPage'
import GesturesPage from './pages/GesturesPage'
import DataFlowPage from './pages/DataFlowPage'
import ArchitecturePage from './pages/ArchitecturePage'
import LifecyclePage from './pages/LifecyclePage'
import ComponentsPage from './pages/ComponentsPage'
import NetworkingPage from './pages/NetworkingPage'
import PersistencePage from './pages/PersistencePage'
import TestingPerfPage from './pages/TestingPerfPage'
import AppLifecycleInterop from './pages/AppLifecycleInterop'
import AccessibilityPage from './pages/AccessibilityPage'
import ThemeToggle from './components/ThemeToggle'

export default function App() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [sidebarCollapsed, setSidebarCollapsed] = useState(() => localStorage.getItem('swiftui-sidebar-collapsed') === 'true')

  const handleNavClick = () => setMobileMenuOpen(false)

  const toggleSidebar = () => {
    setSidebarCollapsed(prev => {
      localStorage.setItem('swiftui-sidebar-collapsed', String(!prev))
      return !prev
    })
  }

  return (
    <>
      <ScrollToTop />
      <header className="mobile-header">
        <button className="hamburger-btn" onClick={() => setMobileMenuOpen(!mobileMenuOpen)} aria-label="Toggle menu">
          {mobileMenuOpen ? '✕' : '☰'}
        </button>
        <h1>📱 SwiftUI 101</h1>
      </header>

      {mobileMenuOpen && <div className="mobile-overlay" onClick={() => setMobileMenuOpen(false)} />}

      <div className={`app-layout ${sidebarCollapsed ? 'layout-collapsed' : ''}`}>
        <aside className={`sidebar ${mobileMenuOpen ? 'sidebar-open' : ''} ${sidebarCollapsed ? 'sidebar-collapsed' : ''}`}>
          <div className="sidebar-header">
            <div className="sidebar-header-top">
              <h1><img src="/logo.svg" alt="" width="28" height="28" style={{ marginRight: '8px' }} /> SwiftUI 101</h1>
              <ThemeToggle />
            </div>
            <p>Декларативный UI для Apple</p>
            <a href={import.meta.env.VITE_DEPLOY_TARGET === 'github-pages' ? new URL('..', window.location.origin + import.meta.env.BASE_URL).toString() : 'http://localhost:3200'} className="back-to-index">← Все плейграунды</a>
          </div>

          <nav className="nav-section">
            <NavLink to="/" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} end onClick={handleNavClick}>
              <span className="nav-link-icon">🏠</span>Главная
            </NavLink>

            <div className="nav-section-title">Основы UI</div>
            <NavLink to="/views" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🎨</span>Views и Modifiers
            </NavLink>
            <NavLink to="/layout" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📐</span>Layout System
            </NavLink>
            <NavLink to="/components" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🧩</span>Компоненты
            </NavLink>

            <div className="nav-section-title">Состояние</div>
            <NavLink to="/state" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📦</span>@State
            </NavLink>
            <NavLink to="/binding" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔗</span>@Binding
            </NavLink>
            <NavLink to="/observable" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">👁️</span>@Observable
            </NavLink>
            <NavLink to="/environment" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🌍</span>Environment
            </NavLink>
            <NavLink to="/data-flow" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔄</span>Data Flow
            </NavLink>

            <div className="nav-section-title">Навигация и списки</div>
            <NavLink to="/navigation" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🧭</span>Navigation
            </NavLink>
            <NavLink to="/lists" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">📋</span>Lists & Forms
            </NavLink>

            <div className="nav-section-title">Анимации и жесты</div>
            <NavLink to="/animations" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">✨</span>Animations
            </NavLink>
            <NavLink to="/gestures" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">👆</span>Gestures
            </NavLink>

            <div className="nav-section-title">Архитектура</div>
            <NavLink to="/lifecycle" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">♻️</span>Lifecycle
            </NavLink>
            <NavLink to="/architecture" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🏛️</span>MVVM
            </NavLink>
            <NavLink to="/app-lifecycle" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🔄</span>App & UIKit Interop
            </NavLink>

            <div className="nav-section-title">Данные и сеть</div>
            <NavLink to="/networking" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🌐</span>Networking
            </NavLink>
            <NavLink to="/persistence" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">💾</span>Хранение данных
            </NavLink>

            <div className="nav-section-title">Качество</div>
            <NavLink to="/accessibility" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">♿</span>Accessibility
            </NavLink>
            <NavLink to="/testing-performance" className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={handleNavClick}>
              <span className="nav-link-icon">🧪</span>Тесты и Performance
            </NavLink>

            <button className="sidebar-collapse-btn" onClick={toggleSidebar}>
              {sidebarCollapsed ? '»' : '«'}<span className="collapse-text">{sidebarCollapsed ? 'Развернуть' : 'Свернуть'}</span>
            </button>
          </nav>
        </aside>

        <main className="main-content">
          <Routes>
            <Route path="/" element={<Home />} />
            <Route path="/views" element={<ViewsModifiersPage />} />
            <Route path="/layout" element={<LayoutPage />} />
            <Route path="/components" element={<ComponentsPage />} />
            <Route path="/state" element={<StatePage />} />
            <Route path="/binding" element={<BindingPage />} />
            <Route path="/observable" element={<ObservablePage />} />
            <Route path="/environment" element={<EnvironmentPage />} />
            <Route path="/data-flow" element={<DataFlowPage />} />
            <Route path="/navigation" element={<NavigationPage />} />
            <Route path="/lists" element={<ListsFormsPage />} />
            <Route path="/animations" element={<AnimationsPage />} />
            <Route path="/gestures" element={<GesturesPage />} />
            <Route path="/lifecycle" element={<LifecyclePage />} />
            <Route path="/architecture" element={<ArchitecturePage />} />
            <Route path="/app-lifecycle" element={<AppLifecycleInterop />} />
            <Route path="/networking" element={<NetworkingPage />} />
            <Route path="/persistence" element={<PersistencePage />} />
            <Route path="/testing-performance" element={<TestingPerfPage />} />
            <Route path="/accessibility" element={<AccessibilityPage />} />
          </Routes>
        </main>
      </div>
    </>
  )
}
